apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
          name: courseconfig
          key: course
    - name: person 
      valueFrom:
        configMapKeyRef:
          name: courseconfig
          key: trainer  
    - name: duration 
      valueFrom:
        configMapKeyRef:
          name: courseconfig
          key: duration
