apiVersion: v1
kind: Pod 
metadata: 
  name: multi-container
labels:
  environment: production   
spec:
  containers:
  - name: nginx-labels
    image: nginx:latest
    ports:
  - name: sidecar
    image: almalinux:8
    command: ["sleep", "200"]