apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels are deployment labels 
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels: # this match labels should atch with pod 
      app: nginx
      project: roboshop
      component: frontend
  template: #this is pod definition 
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend 
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
